### ISSUE TITLE
Do not hardcode duration-seconds

### ISSUE THREAD

**Issue by arkan** [heetch/drone-packer#3]
We should not hardcode `duration-seconds` but instead had a sane default value. 
Example: 
```
iam_creds=$(aws sts assume-role --role-arn "arn:aws:iam::${account_id}:role/${ci_role}" --role-session-name "drone-${session_id}" --duration-seconds ${PLUGIN_AWS_CREDENTIALS_TTL:-'3600'} --region=${PLUGIN_AWS_REGION:-'us-east-1'} | python -m json.tool)
```

**Comment by milit5** [comment]
This change is related to https://github.com/heetch/infra-root-pk-osrm-europe/issues/9 so `PLUGIN_AWS_CREDENTIALS_TTL` needs to be set in [infra-root-pk-osrm-europe ci](https://github.com/heetch/infra-root-pk-osrm-europe/blob/master/.drone.yml).
